-- --------------------------------------------------------
-- 호스트:                          127.0.0.1
-- 서버 버전:                        10.11.15-MariaDB - MariaDB Server
-- 서버 OS:                        Win64
-- HeidiSQL 버전:                  12.14.0.7165
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- 기존 데이터 삭제 (외래키 제약 조건을 잠시 끄고 비웁니다)
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `stickers`;
TRUNCATE TABLE `sticker_categories`;
SET FOREIGN_KEY_CHECKS = 1;

-- 테이블 데이터 nasda.sticker_categories:~7 rows (대략적) 내보내기
INSERT INTO `sticker_categories` (`sticker_category_id`, `is_active`, `name`) VALUES
	(1, b'1', 'Smileys & Emotion'),
	(2, b'1', 'Animals & Nature'),
	(3, b'1', 'Food & Drink'),
	(4, b'1', 'Travel & Places'),
	(5, b'1', 'Activities'),
	(6, b'1', 'Objects'),
	(7, b'1', 'Symbols');

-- 테이블 데이터 nasda.stickers:~210 rows (대략적) 내보내기
INSERT INTO `stickers` (`sticker_id`, `created_at`, `sticker_image_url`, `sticker_name`, `sticker_category_id`) VALUES
	(1, NULL, '/images/Emojis/Smilies/Smiling%20Face%20with%20Hearts.png', 'Smiling Face with Hearts', 1),
	(2, NULL, '/images/Emojis/Smilies/Face%20Blowing%20a%20Kiss.png', 'Face Blowing a Kiss', 1),
	(3, NULL, '/images/Emojis/Smilies/Smiling%20Face%20with%20Smiling%20Eyes.png', 'Smiling Face with Smiling Eyes', 1),
	(4, NULL, '/images/Emojis/Smilies/Heart%20with%20Arrow.png', 'Heart Suit', 1),
	(5, NULL, '/images/Emojis/Smilies/Sparkling%20Heart.png', 'Sparkling Heart', 1),
	(6, NULL, '/images/Emojis/Smilies/Growing%20Heart.png', 'Growing Heart', 1),
	(7, NULL, '/images/Emojis/Smilies/Two%20Hearts.png', 'Two Hearts', 1),
	(8, NULL, '/images/Emojis/Smilies/Love%20Letter.png', 'Love Letter', 1),
	(9, NULL, '/images/Emojis/Smilies/Face%20with%20Hand%20Over%20Mouth.png', 'Face with Hand Over Mouth', 1),
	(10, NULL, '/images/Emojis/Smilies/Star-Struck.png', 'Star-Struck', 1),
	(11, NULL, '/images/Emojis/Smilies/Winking%20Face%20with%20Tongue.png', 'Winking Face with Tongue', 1),
	(12, NULL, '/images/Emojis/Smilies/Partying%20Face.png', 'Partying Face', 1),
	(13, NULL, '/images/Emojis/Smilies/Smiling%20Face%20with%20Halo.png', 'Smiling Face with Halo', 1),
	(14, NULL, '/images/Emojis/Smilies/Hugging%20Face.png', 'Hugging Face', 1),
	(15, NULL, '/images/Emojis/Smilies/Thinking%20Face.png', 'Thinking Face', 1),
	(16, NULL, '/images/Emojis/Smilies/Relieved%20Face.png', 'Relieved Face', 1),
	(17, NULL, '/images/Emojis/Smilies/Upside-Down%20Face.png', 'Upside-Down Face', 1),
	(18, NULL, '/images/Emojis/Smilies/Sleepy%20Face.png', 'Sleepy Face', 1),
	(19, NULL, '/images/Emojis/Smilies/Face%20with%20Monocle.png', 'Face with Monocle', 1),
	(20, NULL, '/images/Emojis/Smilies/Smiling%20Face%20with%20Sunglasses.png', 'Smiling Face with Sun Glasses', 1),
	(21, NULL, '/images/Emojis/Smilies/Dizzy%20Face.png', 'Dizzy Face', 1),
	(22, NULL, '/images/Emojis/Smilies/Ghost.png', 'Ghost', 1),
	(23, NULL, '/images/Emojis/Smilies/Alien.png', 'Alien', 1),
	(24, NULL, '/images/Emojis/Smilies/Cat%20Face%20with%20Heart-Eyes.png', 'Cat Face with Heart-Eyes', 1),
	(25, NULL, '/images/Emojis/Smilies/Kissing%20Cat.png', 'Kissing Cat', 1),
	(26, NULL, '/images/Emojis/Smilies/Red%20Heart.png', 'Red Heart', 1),
	(27, NULL, '/images/Emojis/Smilies/Heart%20on%20Fire.png', 'Heart on Fire', 1),
	(28, NULL, '/images/Emojis/Smilies/Mending%20Heart.png', 'Mending Heart', 1),
	(29, NULL, '/images/Emojis/Smilies/Sparkles.png', 'Sparkles', 1),
	(30, NULL, '/images/Emojis/Smilies/Collision.png', 'Collision', 1),
	(31, NULL, '/images/Emojis/Animals/Bear.png', 'Bear', 2),
	(32, NULL, '/images/Emojis/Animals/Panda.png', 'Panda', 2),
	(33, NULL, '/images/Emojis/Animals/Koala.png', 'Koala', 2),
	(34, NULL, '/images/Emojis/Animals/Rabbit%20Face.png', 'Rabbit Face', 2),
	(35, NULL, '/images/Emojis/Animals/Cat%20Face.png', 'Cat Face', 2),
	(36, NULL, '/images/Emojis/Animals/Dog%20Face.png', 'Dog Face', 2),
	(37, NULL, '/images/Emojis/Animals/Hatching%20Chick.png', 'Hatching Chick', 2),
	(38, NULL, '/images/Emojis/Animals/Butterfly.png', 'Butterfly', 2),
	(39, NULL, '/images/Emojis/Animals/Unicorn.png', 'Unicorn', 2),
	(40, NULL, '/images/Emojis/Animals/Honeybee.png', 'Bee', 2),
	(41, NULL, '/images/Emojis/Animals/Lady%20Beetle.png', 'Lady Beetle', 2),
	(42, NULL, '/images/Emojis/Animals/Penguin.png', 'Penguin', 2),
	(43, NULL, '/images/Emojis/Animals/Dove.png', 'Dove', 2),
	(44, NULL, '/images/Emojis/Animals/Monkey%20Face.png', 'Monkey Face', 2),
	(45, NULL, '/images/Emojis/Animals/Sloth.png', 'Sloth', 2),
	(46, NULL, '/images/Emojis/Animals/Otter.png', 'Otter', 2),
	(47, NULL, '/images/Emojis/Animals/Seal.png', 'Seal', 2),
	(48, NULL, '/images/Emojis/Animals/Spouting%20Whale.png', 'Spouting Whale', 2),
	(49, NULL, '/images/Emojis/Animals/Cherry%20Blossom.png', 'Cherry Blossom', 2),
	(50, NULL, '/images/Emojis/Animals/Tulip.png', 'Tulip', 2),
	(51, NULL, '/images/Emojis/Animals/Sunflower.png', 'Sun Flower', 2),
	(52, NULL, '/images/Emojis/Animals/Four%20Leaf%20Clover.png', 'Four Leaf Clover', 2),
	(53, NULL, '/images/Emojis/Animals/Rainbow.png', 'Rainbow', 2),
	(54, NULL, '/images/Emojis/Animals/Cloud%20with%20Rain.png', 'Cloud with Rain', 2),
	(55, NULL, '/images/Emojis/Animals/Sun%20Behind%20Cloud.png', 'Sun behind Cloud', 2),
	(56, NULL, '/images/Emojis/Animals/Moon%20Viewing%20Ceremony.png', 'Moon Viewing Ceremony', 2),
	(57, NULL, '/images/Emojis/Animals/Hibiscus.png', 'Hibiscus', 2),
	(58, NULL, '/images/Emojis/Animals/Seedling.png', 'Seedling', 2),
	(59, NULL, '/images/Emojis/Animals/Deciduous%20Tree.png', 'Deciduous Tree', 2),
	(60, NULL, '/images/Emojis/Animals/Cactus.png', 'Cactus', 2),
	(61, NULL, '/images/Emojis/Food/Birthday%20Cake.png', 'Birthday Cake', 3),
	(62, NULL, '/images/Emojis/Food/Cupcake.png', 'Cupcake', 3),
	(63, NULL, '/images/Emojis/Food/Shortcake.png', 'Shortcake', 3),
	(64, NULL, '/images/Emojis/Food/Pancakes.png', 'Pancakes', 3),
	(65, NULL, '/images/Emojis/Food/Doughnut.png', 'Doughnut', 3),
	(66, NULL, '/images/Emojis/Food/Cookie.png', 'Cookie', 3),
	(67, NULL, '/images/Emojis/Food/Chocolate%20Bar.png', 'Chocolate Bar', 3),
	(68, NULL, '/images/Emojis/Food/Candy.png', 'Candy', 3),
	(69, NULL, '/images/Emojis/Food/Lollipop.png', 'Lollipop', 3),
	(70, NULL, '/images/Emojis/Food/Custard.png', 'Custard', 3),
	(71, NULL, '/images/Emojis/Food/Ice%20Cream.png', 'Ice Cream', 3),
	(72, NULL, '/images/Emojis/Food/Soft%20Serve.png', 'Soft Ice Cream', 3),
	(73, NULL, '/images/Emojis/Food/Shaved%20Ice.png', 'Shaved Ice', 3),
	(74, NULL, '/images/Emojis/Food/Cherries.png', 'Cherry', 3),
	(75, NULL, '/images/Emojis/Food/Strawberry.png', 'Strawberry', 3),
	(76, NULL, '/images/Emojis/Food/Peach.png', 'Peach', 3),
	(77, NULL, '/images/Emojis/Food/Red%20Apple.png', 'Red Apple', 3),
	(78, NULL, '/images/Emojis/Food/Banana.png', 'Banana', 3),
	(79, NULL, '/images/Emojis/Food/Grapes.png', 'Grapes', 3),
	(80, NULL, '/images/Emojis/Food/Bubble%20Tea.png', 'Bubble Tea', 3),
	(81, NULL, '/images/Emojis/Food/Hot%20Beverage.png', 'Hot Beverage', 3),
	(82, NULL, '/images/Emojis/Food/Glass%20of%20Milk.png', 'Glass of Milk', 3),
	(83, NULL, '/images/Emojis/Food/Pizza.png', 'Pizza', 3),
	(84, NULL, '/images/Emojis/Food/Hamburger.png', 'Hamburger', 3),
	(85, NULL, '/images/Emojis/Food/French%20Fries.png', 'French Fries', 3),
	(86, NULL, '/images/Emojis/Food/Sandwich.png', 'Sandwich', 3),
	(87, NULL, '/images/Emojis/Food/Spaghetti.png', 'Spaghetti', 3),
	(88, NULL, '/images/Emojis/Food/Popcorn.png', 'Popcorn', 3),
	(89, NULL, '/images/Emojis/Food/Rice%20Ball.png', 'Rice Ball', 3),
	(90, NULL, '/images/Emojis/Food/Dango.png', 'Dango', 3),
	(91, NULL, '/images/Emojis/Travel%20and%20places/Rocket.png', 'Rocket', 4),
	(92, NULL, '/images/Emojis/Travel%20and%20places/Airplane.png', 'Airplane', 4),
	(93, NULL, '/images/Emojis/Travel%20and%20places/Auto%20Rickshaw.png', 'Auto Rickshaw', 4),
	(94, NULL, '/images/Emojis/Travel%20and%20places/Ferris%20Wheel.png', 'Ferris Wheel', 4),
	(95, NULL, '/images/Emojis/Travel%20and%20places/Roller%20Coaster.png', 'Roller Coaster', 4),
	(96, NULL, '/images/Emojis/Travel%20and%20places/Carousel%20Horse.png', 'Carousel Horse', 4),
	(97, NULL, '/images/Emojis/Travel%20and%20places/Mount%20Fuji.png', 'Mount Fuji', 4),
	(98, NULL, '/images/Emojis/Travel%20and%20places/Camping.png', 'Camping', 4),
	(99, NULL, '/images/Emojis/Travel%20and%20places/Beach%20with%20Umbrella.png', 'Beach with Umbrella', 4),
	(100, NULL, '/images/Emojis/Travel%20and%20places/Desert%20Island.png', 'Desert Island', 4),
	(101, NULL, '/images/Emojis/Travel%20and%20places/Castle.png', 'Castle', 4),
	(102, NULL, '/images/Emojis/Travel%20and%20places/Classical%20Building.png', 'Classical Building', 4),
	(103, NULL, '/images/Emojis/Travel%20and%20places/House%20with%20Garden.png', 'House with Garden', 4),
	(104, NULL, '/images/Emojis/Travel%20and%20places/Statue%20of%20Liberty.png', 'Statue of Liberty', 4),
	(105, NULL, '/images/Emojis/Travel%20and%20places/Tokyo%20Tower.png', 'Tokyo Tower', 4),
	(106, NULL, '/images/Emojis/Travel%20and%20places/🗼.png', 'Eiffel Tower', 4),
	(107, NULL, '/images/Emojis/Travel%20and%20places/National%20Park.png', 'National Park', 4),
	(108, NULL, '/images/Emojis/Travel%20and%20places/Snow-Capped%20Mountain.png', 'Snow Capped Mountain', 4),
	(109, NULL, '/images/Emojis/Travel%20and%20places/Full%20Moon.png', 'Full Moon', 4),
	(110, NULL, '/images/Emojis/Travel%20and%20places/First%20Quarter%20Moon%20Face.png', 'First Quarter Moon Face', 4),
	(111, NULL, '/images/Emojis/Travel%20and%20places/Sun%20with%20Face.png', 'Sun with Face', 4),
	(112, NULL, '/images/Emojis/Travel%20and%20places/Star.png', 'Star', 4),
	(113, NULL, '/images/Emojis/Travel%20and%20places/Shooting%20Star.png', 'Shooting Star', 4),
	(114, NULL, '/images/Emojis/Travel%20and%20places/Milky%20Way.png', 'Milky Way', 4),
	(115, NULL, '/images/Emojis/Travel%20and%20places/Bicycle.png', 'Bicycle', 4),
	(116, NULL, '/images/Emojis/Travel%20and%20places/Sailboat.png', 'Sailboat', 4),
	(117, NULL, '/images/Emojis/Travel%20and%20places/Anchor.png', 'Anchor', 4),
	(118, NULL, '/images/Emojis/Travel%20and%20places/Fountain.png', 'Fountain', 4),
	(119, NULL, '/images/Emojis/Travel%20and%20places/Foggy.png', 'Foggy', 4),
	(120, NULL, '/images/Emojis/Travel%20and%20places/Fire.png', 'Fire', 4),
	(121, NULL, '/images/Emojis/Activities/Balloon.png', 'Balloon', 5),
	(122, NULL, '/images/Emojis/Activities/Party%20Popper.png', 'Party Popper', 5),
	(123, NULL, '/images/Emojis/Activities/Confetti%20Ball.png', 'Confetti Ball', 5),
	(124, NULL, '/images/Emojis/Activities/Teddy%20Bear.png', 'Teddy Bear', 5),
	(125, NULL, '/images/Emojis/Activities/Carp%20Streamer.png', 'Carp Streamer', 5),
	(126, NULL, '/images/Emojis/Activities/Crystal%20Ball.png', 'Crystal Ball', 5),
	(127, NULL, '/images/Emojis/Activities/Game%20Die.png', 'Game Die', 5),
	(128, NULL, '/images/Emojis/Activities/Jack-O-Lantern.png', 'Jack-O-Lantern', 5),
	(129, NULL, '/images/Emojis/Activities/Magic%20Wand.png', 'Magic Wand', 5),
	(130, NULL, '/images/Emojis/Activities/Nazar%20Amulet.png', 'Nazar Amulet', 5),
	(131, NULL, '/images/Emojis/Activities/Sparkler.png', 'Sparkler', 5),
	(132, NULL, '/images/Emojis/Activities/Wind%20Chime.png', 'Wind Chime', 5),
	(133, NULL, '/images/Emojis/Activities/Artist%20Palette.png', 'Artist Palette', 5),
	(134, NULL, '/images/Emojis/Activities/Circus%20Tent.png', 'Circus Tent', 5),
	(135, NULL, '/images/Emojis/Activities/Slot%20Machine.png', 'Slot Machine', 5),
	(136, NULL, '/images/Emojis/Activities/Yo-Yo.png', 'Yo-Yo', 5),
	(137, NULL, '/images/Emojis/Activities/Kite.png', 'Kite', 5),
	(138, NULL, '/images/Emojis/Activities/Pool%208%20Ball.png', 'Pool 8 Ball', 5),
	(139, NULL, '/images/Emojis/Activities/Skateboard.png', 'Skateboard', 5),
	(140, NULL, '/images/Emojis/Activities/Trophy.png', 'Trophi', 5),
	(141, NULL, '/images/Emojis/Activities/Video%20Game.png', 'Video Game', 5),
	(142, NULL, '/images/Emojis/Activities/Firecracker.png', 'Firecracker', 5),
	(143, NULL, '/images/Emojis/Activities/Red%20Envelope.png', 'Red Envelope', 5),
	(144, NULL, '/images/Emojis/Activities/Clapper%20Board.png', 'Clapper Board', 5),
	(145, NULL, '/images/Emojis/Activities/Headphone.png', 'Headphone', 5),
	(146, NULL, '/images/Emojis/Activities/Microphone.png', 'Microphone', 5),
	(147, NULL, '/images/Emojis/Activities/Musical%20Note.png', 'Musical Note', 5),
	(148, NULL, '/images/Emojis/Activities/Trumpet.png', 'Trumpet', 5),
	(149, NULL, '/images/Emojis/Activities/Violin.png', 'Violin', 5),
	(150, NULL, '/images/Emojis/Activities/Yarn.png', 'Yarn', 5),
	(151, NULL, '/images/Emojis/Objects/Gem%20Stone.png', 'Gem Stone', 6),
	(152, NULL, '/images/Emojis/Objects/Ring.png', 'Ring', 6),
	(153, NULL, '/images/Emojis/Objects/Lipstick.png', 'Lipstick', 6),
	(154, NULL, '/images/Emojis/Objects/Crown.png', 'Crown', 6),
	(155, NULL, '/images/Emojis/Objects/Handbag.png', 'Handbag', 6),
	(156, NULL, '/images/Emojis/Objects/Glass%20Slipper.png', 'Glass Slipper', 6),
	(157, NULL, '/images/Emojis/Objects/Wrapped%20Gift.png', 'Gift', 6),
	(158, NULL, '/images/Emojis/Objects/Camera%20with%20Flash.png', 'Camera', 6),
	(159, NULL, '/images/Emojis/Objects/Candle.png', 'Candle', 6),
	(160, NULL, '/images/Emojis/Objects/Flashlight.png', 'Flashlight', 6),
	(161, NULL, '/images/Emojis/Objects/Mirror.png', 'Mirror', 6),
	(162, NULL, '/images/Emojis/Objects/Soap.png', 'Soap', 6),
	(163, NULL, '/images/Emojis/Objects/Sponge.png', 'Sponge', 6),
	(164, NULL, '/images/Emojis/Objects/Key.png', 'Key', 6),
	(165, NULL, '/images/Emojis/Objects/Laptop.png', 'Laptop', 6),
	(166, NULL, '/images/Emojis/Objects/Mobile%20Phone.png', 'Mobile Phone', 6),
	(167, NULL, '/images/Emojis/Objects/Pencil.png', 'Pencil', 6),
	(168, NULL, '/images/Emojis/Objects/Books.png', 'Books', 6),
	(169, NULL, '/images/Emojis/Objects/Money%20Bag.png', 'Money Bag', 6),
	(170, NULL, '/images/Emojis/Objects/Credit%20Card.png', 'Credit Card', 6),
	(171, NULL, '/images/Emojis/Objects/Alarm%20Clock.png', 'Alarm Clock', 6),
	(172, NULL, '/images/Emojis/Objects/Hourglass%20Done.png', 'Hourglass', 6),
	(173, NULL, '/images/Emojis/Objects/Magnifying%20Glass%20Tilted%20Left.png', 'Magnifying Glass', 6),
	(174, NULL, '/images/Emojis/Objects/Pushpin.png', 'Pushpin', 6),
	(175, NULL, '/images/Emojis/Objects/Umbrella.png', 'Umbrella', 6),
	(176, NULL, '/images/Emojis/Objects/Fire%20Extinguisher.png', 'Fire Extinguisher', 6),
	(177, NULL, '/images/Emojis/Objects/Shopping%20Cart.png', 'Shopping Cart', 6),
	(178, NULL, '/images/Emojis/Objects/Hammer.png', 'Hammer', 6),
	(179, NULL, '/images/Emojis/Objects/Toolbox.png', 'Toolbox', 6),
	(180, NULL, '/images/Emojis/Objects/Ribbon.png', 'Ribbon', 6),
	(181, NULL, '/images/Emojis/Symbols/Heart%20Decoration.png', 'Heart Decoration', 7),
	(182, NULL, '/images/Emojis/Symbols/Peace%20Symbol.png', 'Peace Symbol', 7),
	(183, NULL, '/images/Emojis/Symbols/Check%20Mark%20Button.png', 'Check Mark', 7),
	(184, NULL, '/images/Emojis/Symbols/Double%20Curly%20Loop.png', 'Double Curly Loop', 7),
	(185, NULL, '/images/Emojis/Symbols/Infinity.png', 'Infinity', 7),
	(186, NULL, '/images/Emojis/Symbols/Aries.png', 'Aries', 7),
	(187, NULL, '/images/Emojis/Symbols/Taurus.png', 'Taurus', 7),
	(188, NULL, '/images/Emojis/Symbols/Gemini.png', 'Gemini', 7),
	(189, NULL, '/images/Emojis/Symbols/Cancer.png', 'Cancer', 7),
	(190, NULL, '/images/Emojis/Symbols/Leo.png', 'Leo', 7),
	(191, NULL, '/images/Emojis/Symbols/Virgo.png', 'Virgo', 7),
	(192, NULL, '/images/Emojis/Symbols/Libra.png', 'Libra', 7),
	(193, NULL, '/images/Emojis/Symbols/Scorpio.png', 'Scorpio', 7),
	(194, NULL, '/images/Emojis/Symbols/Sagittarius.png', 'Sagittarius', 7),
	(195, NULL, '/images/Emojis/Symbols/Capricorn.png', 'Capricorn', 7),
	(196, NULL, '/images/Emojis/Symbols/Aquarius.png', 'Aquarius', 7),
	(197, NULL, '/images/Emojis/Symbols/Pisces.png', 'Pisces', 7),
	(198, NULL, '/images/Emojis/Symbols/Sparkles.png', 'Sparkles', 7),
	(199, NULL, '/images/Emojis/Symbols/Eight-Pointed%20Star.png', 'Eight-Pointed Star', 7),
	(200, NULL, '/images/Emojis/Symbols/Recycling%20Symbol.png', 'Recycling Symbol', 7),
	(201, NULL, '/images/Emojis/Symbols/Trident%20Emblem.png', 'Trident Emblem', 7),
	(202, NULL, '/images/Emojis/Symbols/Warning.png', 'Warning', 7),
	(203, NULL, '/images/Emojis/Symbols/Biohazard.png', 'Biohazard', 7),
	(204, NULL, '/images/Emojis/Symbols/Muted%20Speaker.png', 'Muted Speaker', 7),
	(205, NULL, '/images/Emojis/Symbols/Vibration%20Mode.png', 'Vibration Mode', 7),
	(206, NULL, '/images/Emojis/Symbols/Bright%20Button.png', 'Bright Button', 7),
	(207, NULL, '/images/Emojis/Symbols/Blue%20Circle.png', 'Blue Circle', 7),
	(208, NULL, '/images/Emojis/Symbols/Green%20Circle.png', 'Green Circle', 7),
	(209, NULL, '/images/Emojis/Symbols/Purple%20Circle.png', 'Purple Circle', 7),
	(210, NULL, '/images/Emojis/Symbols/White%20Flower.png', 'White Flower', 7);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
